import type { EnvironmentScan, ProjectMetadata } from "./types";

const now = new Date().toISOString();

export const mockProjects: ProjectMetadata[] = [
  {
    name: "easy-package",
    path: "~/Code/easy-package",
    ecosystems: ["JavaScript", "Python"],
    lockFiles: ["pnpm-lock.yaml", "uv.lock"],
    runtimeRequirements: [
      { runtime: "Node.js", requirement: ">=22" },
      { runtime: "Python", requirement: ">=3.12" },
    ],
    packageManager: "pnpm@11.5.3",
    workspace: { name: "developer-tools", path: "~/Code", ecosystem: "JavaScript" },
    dependencies: [
      { ecosystem: "JavaScript", name: "react", normalizedName: "react", versionRequirement: "^19.0.0", scopes: ["运行"], resolvedVersion: "19.1.1", resolutionSource: "pnpm-lock.yaml", resolutionChecked: true },
      { ecosystem: "JavaScript", name: "vitest", normalizedName: "vitest", versionRequirement: "^3.2.0", scopes: ["开发"], resolvedVersion: "3.2.4", resolutionSource: "pnpm-lock.yaml", resolutionChecked: true },
      { ecosystem: "Python", name: "httpx", normalizedName: "httpx", versionRequirement: ">=0.28", scopes: ["运行"], resolvedVersion: "0.28.1", resolutionSource: "uv.lock", resolutionChecked: true },
    ],
    warnings: [],
  },
  {
    name: "api-lab",
    path: "~/Code/api-lab",
    ecosystems: ["Python"],
    lockFiles: ["requirements.txt"],
    runtimeRequirements: [{ runtime: "Python", requirement: ">=3.11" }],
    dependencies: [
      { ecosystem: "Python", name: "httpx", normalizedName: "httpx", versionRequirement: ">=0.27", scopes: ["requirements.txt"], resolutionChecked: false },
      { ecosystem: "Python", name: "pydantic", normalizedName: "pydantic", versionRequirement: ">=2.0", scopes: ["requirements.txt"], resolutionChecked: false },
    ],
    workspace: { name: "developer-tools", path: "~/Code", ecosystem: "JavaScript" },
    warnings: [],
  },
  {
    name: "poetry-app",
    path: "~/Code/poetry-app",
    ecosystems: ["Python"],
    lockFiles: ["poetry.lock"],
    runtimeRequirements: [{ runtime: "Python", requirement: ">=3.12" }],
    packageManager: "poetry",
    dependencies: [
      { ecosystem: "Python", name: "pytest", normalizedName: "pytest", versionRequirement: "^8", scopes: ["开发:dev"], resolvedVersion: "8.3.4", resolutionSource: "poetry.lock", resolutionChecked: true },
    ],
    warnings: [],
  },
  {
    name: "example.com/tool",
    path: "~/Code/go-tool",
    ecosystems: ["Go"],
    lockFiles: ["go.mod", "go.sum"],
    runtimeRequirements: [{ runtime: "Go", requirement: "1.23" }],
    packageManager: "go",
    dependencies: [
      { ecosystem: "Go", name: "github.com/spf13/cobra", normalizedName: "github.com/spf13/cobra", versionRequirement: "v1.8.1", scopes: ["运行"], resolvedVersion: "v1.8.1", resolutionSource: "go.mod", resolutionChecked: true },
    ],
    warnings: [],
  },
  {
    name: "rails-service",
    path: "~/Code/rails-service",
    ecosystems: ["Ruby"],
    lockFiles: ["Gemfile.lock"],
    runtimeRequirements: [{ runtime: "Ruby", requirement: "3.4.1" }],
    packageManager: "bundler",
    dependencies: [
      { ecosystem: "Ruby", name: "rails", normalizedName: "rails", versionRequirement: "~> 8.0", scopes: ["运行"], resolvedVersion: "8.0.1", resolutionSource: "Gemfile.lock", resolutionChecked: true },
      { ecosystem: "Ruby", name: "rspec-rails", normalizedName: "rspec-rails", versionRequirement: "~> 7.1", scopes: ["开发"], resolvedVersion: "7.1.1", resolutionSource: "Gemfile.lock", resolutionChecked: true },
    ],
    warnings: [],
  },
  {
    name: "acme/api",
    path: "~/Code/php-api",
    ecosystems: ["PHP"],
    lockFiles: ["composer.lock"],
    runtimeRequirements: [{ runtime: "PHP", requirement: "^8.3" }],
    packageManager: "composer",
    dependencies: [
      { ecosystem: "PHP", name: "symfony/http-foundation", normalizedName: "symfony/http-foundation", versionRequirement: "^7.2", scopes: ["运行"], resolvedVersion: "v7.2.1", resolutionSource: "composer.lock", resolutionChecked: true },
      { ecosystem: "PHP", name: "phpunit/phpunit", normalizedName: "phpunit/phpunit", versionRequirement: "^11.5", scopes: ["开发"], resolvedVersion: "11.5.3", resolutionSource: "composer.lock", resolutionChecked: true },
    ],
    warnings: [],
  },
  {
    name: "yarn-portal",
    path: "~/Code/yarn-portal",
    ecosystems: ["JavaScript"],
    lockFiles: ["yarn.lock"],
    runtimeRequirements: [{ runtime: "Node.js", requirement: ">=22" }],
    packageManager: "yarn@4.6.0",
    dependencies: [
      { ecosystem: "JavaScript", name: "zod", normalizedName: "zod", versionRequirement: "^3.24.0", scopes: ["运行"], resolvedVersion: "3.24.1", resolutionSource: "yarn.lock", resolutionChecked: true },
    ],
    warnings: [],
  },
  {
    name: "bun-api",
    path: "~/Code/bun-api",
    ecosystems: ["JavaScript"],
    lockFiles: ["bun.lock"],
    runtimeRequirements: [{ runtime: "Bun", requirement: "1.3.0" }],
    packageManager: "bun@1.3.0",
    dependencies: [
      { ecosystem: "JavaScript", name: "hono", normalizedName: "hono", versionRequirement: "^4.6.0", scopes: ["运行"], resolvedVersion: "4.6.14", resolutionSource: "bun.lock", resolutionChecked: true },
    ],
    warnings: [],
  },
];

export const mockScan: EnvironmentScan = {
  managers: [
    { id: "homebrew", displayName: "Homebrew", version: "4.6.15", executablePath: "/opt/homebrew/bin/brew", status: "available", capabilities: ["packages", "outdated", "cache"], cacheSizeBytes: 1_420_000_000, scannedAt: now },
    { id: "npm", displayName: "npm", version: "11.5.1", executablePath: "/opt/homebrew/bin/npm", status: "available", capabilities: ["packages", "outdated", "cache"], cacheSizeBytes: 382_000_000, scannedAt: now },
    { id: "pnpm", displayName: "pnpm", version: "11.5.3", executablePath: "~/.local/share/pnpm/pnpm", status: "available", capabilities: ["packages", "outdated", "cache"], cacheSizeBytes: 3_840_000_000, scannedAt: now },
    { id: "uv", displayName: "uv", version: "0.8.13", executablePath: "~/.local/bin/uv", status: "available", capabilities: ["packages", "cache"], cacheSizeBytes: 694_000_000, scannedAt: now },
    { id: "pip", displayName: "pip", version: "25.2", executablePath: "/opt/homebrew/bin/pip3", status: "available", capabilities: ["packages", "outdated", "cache"], cacheSizeBytes: 121_000_000, scannedAt: now },
    { id: "yarn", displayName: "Yarn", version: "1.22.19", executablePath: "/opt/homebrew/bin/yarn", status: "available", capabilities: ["packages"], scannedAt: now },
    { id: "bun", displayName: "Bun", version: "1.3.14", executablePath: "~/.bun/bin/bun", status: "available", capabilities: ["packages", "cache"], cacheSizeBytes: 512_000_000, scannedAt: now },
    { id: "cargo", displayName: "Cargo", version: "1.84.0", executablePath: "/opt/homebrew/bin/cargo", status: "available", capabilities: ["packages", "cache"], cacheSizeBytes: 840_000_000, scannedAt: now },
    { id: "rubygems", displayName: "RubyGems", version: "3.6.3", executablePath: "/opt/homebrew/bin/gem", status: "available", capabilities: ["packages"], scannedAt: now },
    { id: "composer", displayName: "Composer", version: "2.8.6", executablePath: "/opt/homebrew/bin/composer", status: "available", capabilities: ["packages", "cache"], cacheSizeBytes: 74_000_000, scannedAt: now },
  ],
  packages: [
    { id: "homebrew:git", managerId: "homebrew", name: "git", version: "2.49.0", latestVersion: "2.50.1", scope: "system", updateStatus: "available" },
    { id: "homebrew:ripgrep", managerId: "homebrew", name: "ripgrep", version: "14.1.1", latestVersion: "14.1.1", scope: "system", updateStatus: "upToDate" },
    { id: "npm:typescript", managerId: "npm", name: "typescript", version: "5.8.3", latestVersion: "5.9.2", scope: "global", updateStatus: "available" },
    { id: "pnpm:pnpm", managerId: "pnpm", name: "pnpm", version: "11.5.3", latestVersion: "11.5.3", scope: "global", updateStatus: "upToDate" },
    { id: "uv:httpx", managerId: "uv", name: "httpx", version: "0.28.1", scope: "tool", updateStatus: "unknown" },
    { id: "pip:black", managerId: "pip", name: "black", version: "24.10.0", latestVersion: "25.1.0", scope: "global", updateStatus: "available" },
    { id: "yarn:eslint", managerId: "yarn", name: "eslint", version: "9.39.1", scope: "global", updateStatus: "unknown" },
    { id: "bun:typescript", managerId: "bun", name: "typescript", version: "5.9.3", scope: "global", updateStatus: "unknown" },
    { id: "cargo:ripgrep", managerId: "cargo", name: "ripgrep", version: "14.1.1", scope: "tool", updateStatus: "unknown" },
    { id: "rubygems:rake", managerId: "rubygems", name: "rake", version: "13.2.1", scope: "global", updateStatus: "unknown" },
    { id: "composer:psr/log", managerId: "composer", name: "psr/log", version: "3.0.2", scope: "global", updateStatus: "unknown" },
  ],
  projects: mockProjects,
  dependencyInsights: [
    { ecosystem: "JavaScript", name: "react", projectCount: 1, versionRequirements: ["^19.0.0"], resolvedVersions: ["19.1.1"], projects: [{ projectName: "easy-package", projectPath: "~/Code/easy-package", versionRequirement: "^19.0.0", scopes: ["运行"], resolvedVersion: "19.1.1", resolutionSource: "pnpm-lock.yaml" }], hasVersionDivergence: false, hasResolvedVersionDivergence: false, hasResolutionRisk: false, hasHealthRisk: false },
    { ecosystem: "JavaScript", name: "vitest", projectCount: 1, versionRequirements: ["^3.2.0"], resolvedVersions: ["3.2.4"], projects: [{ projectName: "easy-package", projectPath: "~/Code/easy-package", versionRequirement: "^3.2.0", scopes: ["开发"], resolvedVersion: "3.2.4", resolutionSource: "pnpm-lock.yaml" }], hasVersionDivergence: false, hasResolvedVersionDivergence: false, hasResolutionRisk: false, hasHealthRisk: false },
    { ecosystem: "Python", name: "httpx", projectCount: 2, versionRequirements: [">=0.27", ">=0.28"], resolvedVersions: ["0.28.1"], projects: [{ projectName: "api-lab", projectPath: "~/Code/api-lab", versionRequirement: ">=0.27", scopes: ["requirements.txt"] }, { projectName: "easy-package", projectPath: "~/Code/easy-package", versionRequirement: ">=0.28", scopes: ["运行"], resolvedVersion: "0.28.1", resolutionSource: "uv.lock" }], hasVersionDivergence: true, hasResolvedVersionDivergence: false, hasResolutionRisk: false, hasHealthRisk: true },
    { ecosystem: "Python", name: "pydantic", projectCount: 1, versionRequirements: [">=2.0"], resolvedVersions: [], projects: [{ projectName: "api-lab", projectPath: "~/Code/api-lab", versionRequirement: ">=2.0", scopes: ["requirements.txt"] }], hasVersionDivergence: false, hasResolvedVersionDivergence: false, hasResolutionRisk: false, hasHealthRisk: false },
    { ecosystem: "Python", name: "pytest", projectCount: 1, versionRequirements: ["^8"], resolvedVersions: ["8.3.4"], projects: [{ projectName: "poetry-app", projectPath: "~/Code/poetry-app", versionRequirement: "^8", scopes: ["开发:dev"], resolvedVersion: "8.3.4", resolutionSource: "poetry.lock" }], hasVersionDivergence: false, hasResolvedVersionDivergence: false, hasResolutionRisk: false, hasHealthRisk: false },
    { ecosystem: "Go", name: "github.com/spf13/cobra", projectCount: 1, versionRequirements: ["v1.8.1"], resolvedVersions: ["v1.8.1"], projects: [{ projectName: "example.com/tool", projectPath: "~/Code/go-tool", versionRequirement: "v1.8.1", scopes: ["运行"], resolvedVersion: "v1.8.1", resolutionSource: "go.mod" }], hasVersionDivergence: false, hasResolvedVersionDivergence: false, hasResolutionRisk: false, hasHealthRisk: false },
    { ecosystem: "Ruby", name: "rails", projectCount: 1, versionRequirements: ["~> 8.0"], resolvedVersions: ["8.0.1"], projects: [{ projectName: "rails-service", projectPath: "~/Code/rails-service", versionRequirement: "~> 8.0", scopes: ["运行"], resolvedVersion: "8.0.1", resolutionSource: "Gemfile.lock" }], hasVersionDivergence: false, hasResolvedVersionDivergence: false, hasResolutionRisk: false, hasHealthRisk: false },
    { ecosystem: "Ruby", name: "rspec-rails", projectCount: 1, versionRequirements: ["~> 7.1"], resolvedVersions: ["7.1.1"], projects: [{ projectName: "rails-service", projectPath: "~/Code/rails-service", versionRequirement: "~> 7.1", scopes: ["开发"], resolvedVersion: "7.1.1", resolutionSource: "Gemfile.lock" }], hasVersionDivergence: false, hasResolvedVersionDivergence: false, hasResolutionRisk: false, hasHealthRisk: false },
    { ecosystem: "PHP", name: "symfony/http-foundation", projectCount: 1, versionRequirements: ["^7.2"], resolvedVersions: ["v7.2.1"], projects: [{ projectName: "acme/api", projectPath: "~/Code/php-api", versionRequirement: "^7.2", scopes: ["运行"], resolvedVersion: "v7.2.1", resolutionSource: "composer.lock" }], hasVersionDivergence: false, hasResolvedVersionDivergence: false, hasResolutionRisk: false, hasHealthRisk: false },
    { ecosystem: "PHP", name: "phpunit/phpunit", projectCount: 1, versionRequirements: ["^11.5"], resolvedVersions: ["11.5.3"], projects: [{ projectName: "acme/api", projectPath: "~/Code/php-api", versionRequirement: "^11.5", scopes: ["开发"], resolvedVersion: "11.5.3", resolutionSource: "composer.lock" }], hasVersionDivergence: false, hasResolvedVersionDivergence: false, hasResolutionRisk: false, hasHealthRisk: false },
    { ecosystem: "JavaScript", name: "zod", projectCount: 1, versionRequirements: ["^3.24.0"], resolvedVersions: ["3.24.1"], projects: [{ projectName: "yarn-portal", projectPath: "~/Code/yarn-portal", versionRequirement: "^3.24.0", scopes: ["运行"], resolvedVersion: "3.24.1", resolutionSource: "yarn.lock" }], hasVersionDivergence: false, hasResolvedVersionDivergence: false, hasResolutionRisk: false, hasHealthRisk: false },
    { ecosystem: "JavaScript", name: "hono", projectCount: 1, versionRequirements: ["^4.6.0"], resolvedVersions: ["4.6.14"], projects: [{ projectName: "bun-api", projectPath: "~/Code/bun-api", versionRequirement: "^4.6.0", scopes: ["运行"], resolvedVersion: "4.6.14", resolutionSource: "bun.lock" }], hasVersionDivergence: false, hasResolvedVersionDivergence: false, hasResolutionRisk: false, hasHealthRisk: false },
  ],
  workspaces: [{ name: "developer-tools", path: "~/Code", ecosystem: "JavaScript", memberPaths: ["~/Code/easy-package", "~/Code/api-lab"] }],
  scanRoots: ["~/Code"],
  healthIssues: [
    { id: "updates", severity: "warning", code: "UPDATES_AVAILABLE", title: "3 个软件包可更新", description: "本版本仅展示更新状态，不会修改本机环境。" },
    { id: "python-path", severity: "info", code: "PATH_CONFLICT", title: "发现多个 Python 路径", description: "当前优先使用 /opt/homebrew/bin/python3，请确认这符合预期。" },
  ],
  logs: [
    { id: "scan-complete", category: "scan", status: "success", message: "环境扫描完成", timestamp: now },
    { id: "uv-outdated", category: "manager", status: "info", message: "uv 当前仅支持已安装工具扫描", managerId: "uv", timestamp: now },
  ],
  pathObservations: [
    { command: "node", activePath: "/opt/homebrew/bin/node", alternatives: ["~/.nvm/versions/node/v22.17.1/bin/node"], hasConflict: true },
    { command: "python3", activePath: "/opt/homebrew/bin/python3", alternatives: ["/usr/bin/python3"], hasConflict: true },
    { command: "npm", activePath: "/opt/homebrew/bin/npm", alternatives: [], hasConflict: false },
    { command: "pip3", activePath: "/opt/homebrew/bin/pip3", alternatives: ["/usr/bin/pip3"], hasConflict: true },
  ],
  scannedAt: now,
  partialFailures: 0,
};
