// 本文件由 src-tauri 的 bindings 测试从 Rust models 生成，请勿手工修改。
// 重新生成：EASY_PACKAGE_EXPORT_TYPES=1 cargo test bindings

// This file has been generated by Specta. DO NOT EDIT.

export type ActionBlockerCode = "READY" | "UNSUPPORTED_PLATFORM" | "MISSING_SCAN" | "RECOVERY_REQUIRED" | "MANAGER_UNAVAILABLE" | "UNTRUSTED_EXECUTABLE" | "RUNTIME_CONFLICT" | "UNSAFE_DATA_PATH" | "PERMISSION_RISK" | "NETWORK_REQUIRED" | "SCRIPTS_DISABLED" | "CACHE_SEMANTICS"

export type ActionCapability = { managerId: PackageManagerId; action: PackageAction; ready: boolean; checks: ActionPreflightCheck[] }

export type ActionCheckStatus = "pass" | "warning" | "blocked"

export type ActionPreflightCheck = { code: ActionBlockerCode; status: ActionCheckStatus; title: string; detail: string }

export type CacheScanStatus = "complete" | "partial" | "unavailable" | "notApplicable"

export type CatalogSearchBlockerCode = "NETWORK_POLICY_OFFLINE" | "INVALID_QUERY" | "UNSUPPORTED_MANAGER" | "MISSING_SCAN" | "MANAGER_UNAVAILABLE" | "UNTRUSTED_EXECUTABLE" | "CANCELLED" | "SEARCH_FAILED"

export type CatalogSearchResponse = { searchId: string; managerId: PackageManagerId; query: string; status: CatalogSearchStatus; blockerCode?: CatalogSearchBlockerCode; message: string; results: CatalogSearchResult[] }

export type CatalogSearchResult = { managerId: PackageManagerId; name: string; description?: string; version?: string; installed: boolean; installedVersion?: string }

export type CatalogSearchStatus = "ready" | "offline" | "invalidQuery" | "managerUnavailable" | "untrustedExecutable" | "cancelled" | "error"

export type DependencyGraphCompleteness = "complete" | "partial" | "unsupported" | "invalid"

export type DependencyGraphEdge = { from: string; to: string; dependencyType: string }

export type DependencyGraphNode = { id: string; ecosystem: string; name: string; version: string; kind: DependencyGraphNodeKind; direct: boolean; scopes: string[]; packageUrl?: string }

export type DependencyGraphNodeKind = "project" | "package" | "local"

export type DependencyGraphSummary = { nodeCount: number; edgeCount: number; directCount: number; transitiveCount: number; duplicateVersionCount: number; unreachableCount: number; cycleCount: number; completeness: DependencyGraphCompleteness; sources: string[]; sourceDigest: string }

export type DependencyInsight = { ecosystem: string; name: string; projectCount: number; versionRequirements: string[]; projects: DependencyProjectUsage[]; hasVersionDivergence: boolean; resolvedVersions: string[]; hasResolvedVersionDivergence: boolean; hasResolutionRisk: boolean; hasHealthRisk: boolean }

export type DependencyProjectUsage = { projectName: string; projectPath: string; versionRequirement: string; scopes: string[]; resolvedVersion?: string; resolutionSource?: string }

export type DiagnosticError = { code: string; message: string; exitCode?: number; output?: string }

export type EnvironmentScan = { managers: PackageManager[]; packages: ManagedPackage[]; projects: ProjectMetadata[]; dependencyInsights: DependencyInsight[]; workspaces: ProjectWorkspace[]; runtimeInstallations: RuntimeInstallation[]; runtimeAssessments: RuntimeRequirementAssessment[]; scanRoots: string[]; scanSettings: ScanSettings; healthIssues: HealthIssue[]; logs: TaskLog[]; pathObservations: PathObservation[]; scannedAt: string; partialFailures: number }

export type ExecutionTrust = "system" | "managed" | "userManaged" | "unverified" | "notApplicable"

export type HealthIssue = { id: string; severity: HealthSeverity; code: string; title: string; description: string; managerId?: PackageManagerId; path?: string; command?: string }

export type HealthSeverity = "info" | "warning" | "error"

export type LogCategory = "scan" | "manager" | "project" | "storage"

export type LogStatus = "info" | "success" | "warning" | "error"

export type ManagedPackage = { id: string; managerId: PackageManagerId; name: string; version: string; latestVersion?: string; scope: PackageScope; updateStatus: UpdateStatus }

export type ManagerStatus = "available" | "unavailable" | "error" | "blocked" | "unsupported"

export type NetworkPolicy = "offline" | "registry"

export type ObservedActionOutcome = "applied" | "notApplied" | "ambiguous"

export type PackageAction = "install" | "upgrade" | "uninstall" | "cleanup"

export type PackageActionAuditRecord = { actionId: string; planId: string; managerId: PackageManagerId; action: PackageAction; targets: string[]; status: PackageActionStatus; commandPreview: string; logs: string[]; error?: string; startedAt: string; finishedAt: string; baselineSnapshotId?: number; resultSnapshotId?: number; observedOutcome?: ObservedActionOutcome; evidence: string[]; reconciledAt?: string; rescanRequired: boolean }

export type PackageActionPlan = { id: string; managerId: PackageManagerId; action: PackageAction; targets: string[]; commandPreview: string; warnings: string[]; previewLines: string[]; checks: ActionPreflightCheck[]; requiresNetwork: boolean; createdAt: string }

export type PackageActionProgress = { actionId: string; status: PackageActionStatus; message: string; cancellable: boolean; timestamp: string }

export type PackageActionReconciliationResult = { audit: PackageActionAuditRecord; environment: EnvironmentScan }

export type PackageActionResult = { actionId: string; planId: string; managerId: PackageManagerId; action: PackageAction; targets: string[]; status: PackageActionStatus; commandPreview: string; logs: string[]; error?: string; comparison?: SnapshotComparison; environment?: EnvironmentScan; startedAt: string; finishedAt: string }

export type PackageActionStatus = "planned" | "running" | "succeeded" | "failed" | "unknown"

export type PackageManager = { id: PackageManagerId; displayName: string; version?: string; executablePath?: string; status: ManagerStatus; executionTrust: ExecutionTrust; capabilities: string[]; error?: DiagnosticError; cacheSizeBytes?: number; cacheScanStatus: CacheScanStatus; scannedAt: string }

export type PackageManagerId = "homebrew" | "npm" | "pnpm" | "uv" | "pip" | "yarn" | "bun" | "cargo" | "rubygems" | "composer"

export type PackageScope = "system" | "global" | "tool"

export type PathCandidate = { path: string; pathIndex: number; managerId?: PackageManagerId; version?: string }

export type PathObservation = { command: string; activePath?: string; alternatives: string[]; hasConflict: boolean; candidates: PathCandidate[] }

export type ProjectAnalysis = { projects: ProjectMetadata[]; dependencyInsights: DependencyInsight[]; workspaces: ProjectWorkspace[]; runtimeAssessments: RuntimeRequirementAssessment[]; healthIssues: HealthIssue[]; scanSettings: ScanSettings }

export type ProjectDependency = { ecosystem: string; name: string; normalizedName: string; versionRequirement: string; scopes: string[]; resolvedVersion?: string; resolutionSource?: string; resolutionChecked: boolean }

export type ProjectDependencyGraph = { projectName: string; projectPath: string; completeness: DependencyGraphCompleteness; sources: string[]; sourceDigest: string; nodes: DependencyGraphNode[]; edges: DependencyGraphEdge[]; warnings: string[]; summary: DependencyGraphSummary }

export type ProjectMetadata = { name: string; path: string; ecosystems: string[]; lockFiles: string[]; runtimeRequirements: RuntimeRequirement[]; packageManager?: string; dependencies: ProjectDependency[]; workspace?: ProjectWorkspaceRef; dependencyGraphSummary?: DependencyGraphSummary; supplyChainRiskSummary?: SupplyChainRiskSummary; warnings: string[] }

export type ProjectSupplyChainReport = { projectName: string; projectPath: string; summary: SupplyChainRiskSummary; findings: SupplyChainRiskFinding[] }

export type ProjectWorkspace = { name: string; path: string; ecosystem: string; memberPaths: string[] }

export type ProjectWorkspaceRef = { name: string; path: string; ecosystem: string }

export type ReportExportResult = { saved: boolean; path?: string }

export type ReportFormat = "json" | "markdown"

export type RuntimeInstallation = { id: string; runtime: string; version: string; path: string; provider: string; isActive: boolean; executionTrust: ExecutionTrust }

export type RuntimeRequirement = { runtime: string; requirement: string }

export type RuntimeRequirementAssessment = { projectName: string; projectPath: string; runtime: string; requirement: string; status: RuntimeRequirementStatus; activeVersion?: string; installedVersions: string[]; message: string }

export type RuntimeRequirementStatus = "available" | "missing" | "mismatch" | "unknown"

export type ScanPhase = "managers" | "projects" | "runtimes" | "health" | "complete"

export type ScanProgress = { scanId: string; phase: ScanPhase; completed: number; total: number; managerId?: PackageManagerId }

export type ScanSettings = { ignoredPaths: string[]; maxDepth: number; defaultIgnoredDirectoryNames: string[]; networkPolicy: NetworkPolicy }

export type SnapshotChange = { kind: SnapshotChangeKind; entity: SnapshotChangeEntity; key: string; title: string; description: string }

export type SnapshotChangeEntity = "manager" | "package" | "project" | "health"

export type SnapshotChangeKind = "added" | "removed" | "changed"

export type SnapshotComparison = { baseline: SnapshotSummary; current: SnapshotSummary; changes: SnapshotChange[]; addedCount: number; removedCount: number; changedCount: number }

export type SnapshotSummary = { id: number; scannedAt: string; managerCount: number; packageCount: number; projectCount: number; healthIssueCount: number }

export type SupplyChainRiskFinding = { id: string; code: string; severity: SupplyChainRiskSeverity; title: string; description: string; projectPath: string; nodeId?: string; dependencyPath: string[]; evidence: string[] }

export type SupplyChainRiskSeverity = "info" | "warning"

export type SupplyChainRiskSummary = { totalCount: number; warningCount: number; infoCount: number; ruleIds: string[] }

export type TaskLog = { id: string; category: LogCategory; status: LogStatus; message: string; managerId?: PackageManagerId; exitCode?: number; output?: string; timestamp: string }

export type UpdateStatus = "upToDate" | "available" | "unknown"

